import React, { useState } from 'react';
import { Check, CreditCard, LockKeyhole, Smartphone, X } from 'lucide-react';

interface PaymentModalProps { title: string; description: string; amount: number; onClose: () => void; onSuccess: (paymentId: string) => void; }

export const PaymentModal: React.FC<PaymentModalProps> = ({ title, description, amount, onClose, onSuccess }) => {
  const [method, setMethod] = useState<'upi' | 'card' | 'netbanking'>('upi');
  const [processing, setProcessing] = useState(false);
  const [paid, setPaid] = useState(false);
  const pay = () => { setProcessing(true); window.setTimeout(() => { setPaid(true); setProcessing(false); window.setTimeout(() => onSuccess(`pay_demo_${Date.now().toString(36).toUpperCase()}`), 700); }, 900); };
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div className="payment-modal w-full max-w-md rounded-2xl p-6 shadow-2xl"><div className="flex items-start justify-between border-b border-neutral-800 pb-4"><div><span className="payment-kicker"><LockKeyhole size={12} /> Secure checkout</span><h2>{title}</h2><p>{description}</p></div><button onClick={onClose} aria-label="Close payment"><X size={18} /></button></div><div className="payment-total"><span>Total payable</span><strong>₹{amount.toLocaleString()}</strong></div>{paid ? <div className="payment-success"><span><Check size={22} /></span><strong>Payment successful</strong><small>Confirming your booking…</small></div> : <><div className="payment-methods">{[['upi', 'UPI', <Smartphone size={16} />], ['card', 'Card', <CreditCard size={16} />], ['netbanking', 'Net banking', <span>↗</span>]].map(([value, label, icon]) => <button key={value as string} className={method === value ? 'active' : ''} onClick={() => setMethod(value as typeof method)}>{icon}<span>{label}</span></button>)}</div><div className="payment-fields">{method === 'upi' && <input placeholder="yourname@upi" aria-label="UPI ID" />}{method === 'card' && <><input placeholder="Card number" aria-label="Card number" /><div><input placeholder="MM / YY" aria-label="Expiry" /><input placeholder="CVV" aria-label="CVV" /></div></>}{method === 'netbanking' && <select aria-label="Bank"><option>Select your bank</option><option>State Bank of India</option><option>HDFC Bank</option><option>ICICI Bank</option><option>Axis Bank</option></select>}</div><button className="payment-pay" onClick={pay} disabled={processing}>{processing ? 'Processing securely…' : `Pay ₹${amount.toLocaleString()}`}<LockKeyhole size={15} /></button><small className="payment-note">Demo checkout enabled · No real money will be charged</small></>}</div></div>;
};
